/**
 * One Open Graph card per language, written to `public/og/`.
 *
 * A link shared into a Brazilian group chat previewed in English, because all
 * seven languages pointed at the one card generated for the English site. The
 * preview is the whole of what most people see before deciding whether to
 * click, so an English card on a Portuguese page is the first — and often the
 * only — thing a reader is shown.
 *
 * **Why a script and not Next's own file convention.** Two arrangements of
 * `opengraph-image.tsx` were tried first:
 *
 *   One at the `[locale]` segment. Next resolves that convention per segment
 *   and does not inherit it, so `/pt-br/` got a Portuguese card and
 *   `/pt-br/devex-rates/` got none at all.
 *
 *   One per localized segment — twenty-nine three-line files, generated. Every
 *   card is prerendered, and the Worker still grew by 0.76 MB compressed, from
 *   2.72 MB to 3.48 MB, because a route under a dynamic segment keeps its
 *   handler in the server bundle whether or not it is `force-static`. That is
 *   over Cloudflare's 3 MB limit: the entire site failing to deploy so that a
 *   preview image can be generated by a Worker that will never be asked for
 *   it.
 *
 * A PNG on disk has neither problem. It is a static asset like any other, it
 * costs the Worker nothing, and its URL is stable enough to write down in
 * metadata.
 *
 * The cards are committed, and `--check` compares each one against a
 * fingerprint of what it was drawn from — the locale, the rate, the minimum
 * and the four strings. A rate change therefore fails the build until the
 * cards are regenerated, rather than leaving six previews quoting a figure the
 * site no longer publishes.
 */

/*
 * Reading a dictionary is not rendering a page.
 *
 * `getTranslator` refuses a locale awaiting native review unless this is set,
 * and that guard exists so an unreviewed language cannot be *served*. This
 * script generates a committed asset from those same words; the asset is only
 * ever reached from a page that is itself gated, and refusing to build it
 * would mean the six cards could not exist until the day the locales publish.
 */
process.env.ENABLE_REVIEW_LOCALES = "true";

import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { getRateValue, minimumEarnedRobux } from "../../src/lib/calculations/rate-registry";
import { standardRateId } from "../../src/lib/calculations/devex";
import { formatCurrency, formatRate, formatRobux } from "../../src/lib/calculations/format";
import { Rational } from "../../src/lib/calculations/rational";
import { getTranslator } from "../../src/i18n/get-dictionary";
import { getLocaleMeta, DEFAULT_LOCALE, LAUNCH_LOCALES } from "../../src/i18n/config";
import { renderOgImage, type OgCard } from "../../src/lib/og/template";
import { englishCardSlug, englishCards } from "../../src/lib/og/english-cards";
import type { Locale } from "../../src/i18n/types";

const ROOT = process.cwd();
const OUT_DIR = join(ROOT, "public/og");
const MANIFEST = join(OUT_DIR, "cards.json");

const WORKED_EXAMPLE = 100_000;

/** The card for one language, and the fingerprint of what it was drawn from. */
async function cardFor(locale: Locale): Promise<{ card: OgCard; fingerprint: string }> {
  const t = await getTranslator(locale, ["seo"]);
  const tag = getLocaleMeta(locale).bcp47;
  const rate = getRateValue(standardRateId);
  const example = Rational.fromInt(WORKED_EXAMPLE).mul(rate);

  const card: OgCard = {
    headline: [t("seo.og.headlineFirst"), t("seo.og.headlineSecond")],
    detail: t("seo.og.detail", {
      robux: formatRobux(tag, WORKED_EXAMPLE),
      usd: formatCurrency(tag, example, "USD"),
      rate: `$${formatRate(tag, rate)}`,
    }),
    footnote: t("seo.og.footnote", { minimum: formatRobux(tag, minimumEarnedRobux) }),
  };

  const fingerprint = createHash("sha256")
    .update(JSON.stringify({ locale, card, alt: t("seo.og.alt") }))
    .digest("hex")
    .slice(0, 16);

  return { card, fingerprint };
}

/*
 * English is here too now.
 *
 * It used to be excluded because Next's file convention produced its cards.
 * That convention gave every one of them a URL with no file extension, and
 * `trailingSlash: true` answers those with a 308 — so every English social
 * preview on the site was a redirect, and the `ImageResponse` runtime behind
 * them was 0.76 MB of a 3 MB Worker. The words moved to
 * `src/lib/og/english-cards.ts`; the drawing happens here, with the same
 * fingerprint check as every other language.
 */
const targets = LAUNCH_LOCALES.filter((locale) => locale !== DEFAULT_LOCALE);
const check = process.argv.includes("--check");

/** The English cards, keyed by the file they are written to. */
function englishTargets(): { name: string; card: OgCard; fingerprint: string }[] {
  return [...englishCards().entries()].map(([route, entry]) => ({
    name: englishCardSlug(route),
    card: entry.card,
    fingerprint: createHash("sha256")
      .update(JSON.stringify({ route, card: entry.card, alt: entry.alt }))
      .digest("hex")
      .slice(0, 16),
  }));
}

async function main(): Promise<void> {
  const expected: Record<string, string> = {};
  const stale: string[] = [];

  mkdirSync(OUT_DIR, { recursive: true });

  const current: Record<string, string> = existsSync(MANIFEST)
    ? (JSON.parse(readFileSync(MANIFEST, "utf8")) as { cards: Record<string, string> }).cards
    : {};

  const drawings: { name: string; card: OgCard; fingerprint: string }[] = [];
  for (const locale of targets) {
    const { card, fingerprint } = await cardFor(locale);
    drawings.push({ name: locale, card, fingerprint });
  }
  drawings.push(...englishTargets());

  for (const { name, card, fingerprint } of drawings) {
    expected[name] = fingerprint;

    const file = join(OUT_DIR, `${name}.png`);
    if (check) {
      if (!existsSync(file) || current[name] !== fingerprint) stale.push(name);
      continue;
    }
    if (existsSync(file) && current[name] === fingerprint) continue;

    const png = Buffer.from(await renderOgImage(card).arrayBuffer());
    writeFileSync(file, png);
    console.log(`  ${name}.png  ${(png.byteLength / 1024).toFixed(0)} kB`);
  }

  const expectedCount = drawings.length;

  if (check) {
    if (stale.length > 0) {
      for (const name of stale) {
        console.error(`  public/og/${name}.png is missing or out of date`);
      }
      console.error("\nRun: npm run og:localized");
      process.exit(1);
    }
    console.log(`Open Graph cards current — ${expectedCount} card(s)`);
  } else {
    writeFileSync(
      MANIFEST,
      `${JSON.stringify(
        {
          $comment:
            "Fingerprints of what each card was drawn from. Regenerate with npm run og:localized; validate:localized-og fails when a card no longer matches the figures on the site.",
          cards: expected,
        },
        null,
        2,
      )}\n`,
      "utf8",
    );
    console.log(`Open Graph cards written — ${expectedCount} card(s)`);
  }

}

void main();
