/**
 * Lifts the reader-facing prose out of the route registry into `en/routes.json`.
 *
 * Run by `npm run i18n:extract-routes`. Deterministic: same registry in, same
 * bytes out, so a diff means the content changed and not that the script ran
 * again.
 *
 * **Why a script and not a hand-written file.** The registry holds roughly a
 * third of everything a reader sees on this site — every title, description,
 * H1, quick answer, section heading, FAQ pair and link anchor for 36 routes.
 * Copying that by hand is how a sentence goes missing silently: nothing fails,
 * one page just quietly loses its answer. Extracting it mechanically means the
 * English dictionary is provably the registry's own words, and the coverage
 * validator then proves every translation matches the English.
 *
 * **What is deliberately left behind.** `primaryKeyword`, `secondaryKeywords`,
 * `primaryIntent` and `entities` are research notes, not prose — they are never
 * rendered, and machine-translating a keyword list produces terms nobody
 * searches for in that language. Localized keyword research is a separate piece
 * of work with a human in it. `route`, `sourceIds`, dates, schema types and
 * every id stay invariant for the obvious reason: they are identifiers.
 *
 * The keys are derived from the route path, so a renamed route shows up as a
 * missing key in six languages rather than as a page that silently falls back.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { routeRegistry } from "../../src/lib/content/route-registry";
import type { RouteRecord } from "../../src/types/content";
import { routeKey } from "../../src/i18n/route-key";

const OUT = join(process.cwd(), "src/i18n/locales/en/routes.json");


interface RouteStrings {
  readonly title: string;
  readonly metaDescription: string;
  readonly h1: string;
  readonly navLabel: string;
  readonly quickAnswer: string;
  readonly ogImageAlt: string;
  readonly sections: Record<string, string>;
  readonly faqs: Record<string, { question: string; answer: string }>;
  readonly links: Record<string, string>;
}

/** Numbered so two FAQs with the same first words cannot collide. */
function faqKey(index: number): string {
  return `q${String(index + 1).padStart(2, "0")}`;
}

/** A link's key is its destination, which is what makes it unique on a page. */
function linkKey(route: string): string {
  return routeKey(route);
}

function extract(record: RouteRecord): RouteStrings {
  const sections: Record<string, string> = {};
  for (const section of record.sections) sections[section.id] = section.heading;

  const faqs: Record<string, { question: string; answer: string }> = {};
  record.faqs.forEach((faq, index) => {
    faqs[faqKey(index)] = { question: faq.question, answer: faq.answer };
  });

  const links: Record<string, string> = {};
  for (const link of record.internalLinks) links[linkKey(link.route)] = link.anchor;

  return {
    title: record.title,
    metaDescription: record.metaDescription,
    h1: record.h1,
    navLabel: record.navLabel,
    quickAnswer: record.quickAnswer,
    ogImageAlt: record.ogImageAlt,
    sections,
    faqs,
    links,
  };
}

const routes = [...routeRegistry].sort((a, b) => a.route.localeCompare(b.route));
const out: Record<string, unknown> = {
  $comment:
    "Generated by scripts/i18n/extract-routes.ts from the route registry. English is the source: edit the registry, then re-run the extractor. Keyword research fields are deliberately absent — they are not prose and are never rendered.",
};

const seen = new Map<string, string>();
for (const record of routes) {
  const key = routeKey(record.route);
  const clash = seen.get(key);
  if (clash) {
    // Two routes mapping to one key would silently overwrite a whole page's
    // words. Loud, and at extraction time rather than in a translation review.
    throw new Error(`Route key "${key}" is claimed by both ${clash} and ${record.route}.`);
  }
  seen.set(key, record.route);
  out[key] = extract(record);
}

writeFileSync(OUT, `${JSON.stringify(out, null, 2)}\n`, "utf8");

const strings = routes.reduce((sum, record) => {
  const s = extract(record);
  return (
    sum +
    6 +
    Object.keys(s.sections).length +
    Object.keys(s.faqs).length * 2 +
    Object.keys(s.links).length
  );
}, 0);
const words = JSON.stringify(routes.map(extract))
  .split(/\s+/)
  .filter(Boolean).length;

console.log(`routes namespace: ${routes.length} routes · ${strings} strings · ~${words} words`);
console.log(`written to ${OUT}`);
