/**
 * Keeps the `data` dictionary in step with the registries it describes.
 *
 * Three files under `src/data/` hold prose as well as figures: the rate
 * registry names and explains each rate, the source registry lists what each
 * citation supports, and the platform metrics file labels every series. That
 * prose is rendered to readers, so it has to be translatable — but it cannot
 * simply be moved into a dictionary, because the same objects carry the
 * numbers, the source ids and the verification dates that the build validates.
 * Splitting them would put a rate's figure and the sentence explaining it in
 * two files that could disagree.
 *
 * So English stays in `src/data/` as the record, and this script mirrors the
 * reader-facing strings into `src/i18n/locales/en/data.json` under keys derived
 * from the ids already in those files. Translations are made against that
 * mirror. `--check` fails when the two have drifted, which is what stops an
 * edited `eligibilitySummary` from silently keeping its old six translations.
 *
 * What is deliberately **not** mirrored:
 *
 *   - `publisher` and `title` on a source. They are the name of an English
 *     document and the organisation that published it. Translating "Developer
 *     Exchange — Help and Information Page" would label a link with a title
 *     that does not exist on the page it opens.
 *   - Period labels (`FY 2024`, `Q2 2026`) and quoted magnitudes (`$1,469M`).
 *     Quoted verbatim from a filing; a translated quotation is not a quotation.
 *   - Anything under `$comment`, which no reader ever sees.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const OUT = join(ROOT, "src/i18n/locales/en/data.json");

function load<T>(name: string): T {
  return JSON.parse(readFileSync(join(ROOT, "src/data", name), "utf8")) as T;
}

interface SourceRow {
  readonly id: string;
  readonly factsSupported: readonly string[];
  readonly evidenceLabel: string;
}
interface RateRow {
  readonly id: string;
  readonly label: string;
  readonly shortLabel: string;
  readonly eligibilitySummary: string;
  readonly conditionNote: string | null;
}
interface SchemeRow {
  readonly id: string;
  readonly label: string;
  readonly description: string;
}
interface Period {
  readonly id: string;
  readonly derivation?: string;
}
interface Series {
  readonly label: string;
  readonly description: string;
  readonly periods: readonly Period[];
}
interface Figure {
  readonly id: string;
  readonly label: string;
  readonly note: string;
}
interface EngagementFigure extends Figure {
  readonly value: string;
  readonly change: string;
}

const sources = load<{ sources: readonly SourceRow[] }>("source-registry.json");
const rates = load<{
  minimum: { note: string };
  limits: { note: string };
  rates: readonly RateRow[];
  marketplace: { schemes: readonly SchemeRow[] };
}>("rates.json");
const currencies = load<{ note: string }>("currencies.json");
const metrics = load<{
  developerExchangeFees: Series;
  revenue: Series;
  shareOfRevenue: Series;
  companyContext: { label: string; description: string; figures: readonly Figure[] };
  engagement: {
    label: string;
    description: string;
    figures: readonly EngagementFigure[];
    notPublished: readonly { id: string; label: string; reason: string }[];
  };
}>("platform-metrics.json");

type Node = string | readonly Node[] | { readonly [k: string]: Node };

/** The distinct evidence labels, keyed by a slug rather than repeated per source. */
const evidenceLabels = [...new Set(sources.sources.map((s) => s.evidenceLabel))];
const evidenceKey = (label: string): string =>
  label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const seriesNode = (series: Series): Node => {
  const node: Record<string, Node> = {
    label: series.label,
    description: series.description,
  };
  const derivations: Record<string, Node> = {};
  for (const period of series.periods) {
    if (period.derivation) derivations[period.id] = period.derivation;
  }
  if (Object.keys(derivations).length > 0) node.derivation = derivations;
  return node;
};

const dictionary: Record<string, Node> = {
  $comment:
    "Generated by scripts/i18n/sync-data-dictionary.ts from src/data/*.json. " +
    "Edit the English in src/data/ and re-run the script; edits made here are overwritten. " +
    "Translations of these keys are written by hand like any other namespace.",

  evidence: Object.fromEntries(evidenceLabels.map((label) => [evidenceKey(label), label])),

  sources: Object.fromEntries(
    sources.sources.map((source) => [source.id, { facts: source.factsSupported.slice() }]),
  ) as Record<string, Node>,

  rates: Object.fromEntries(
    rates.rates.map((rate) => {
      const node: Record<string, Node> = {
        label: rate.label,
        shortLabel: rate.shortLabel,
        eligibilitySummary: rate.eligibilitySummary,
      };
      if (rate.conditionNote !== null) node.conditionNote = rate.conditionNote;
      return [rate.id, node];
    }),
  ) as Record<string, Node>,

  minimum: { note: rates.minimum.note },
  limits: { note: rates.limits.note },

  schemes: Object.fromEntries(
    rates.marketplace.schemes.map((scheme) => [
      scheme.id,
      { label: scheme.label, description: scheme.description },
    ]),
  ) as Record<string, Node>,

  currencies: { note: currencies.note },

  metrics: {
    developerExchangeFees: seriesNode(metrics.developerExchangeFees),
    revenue: seriesNode(metrics.revenue),
    shareOfRevenue: seriesNode(metrics.shareOfRevenue),
    companyContext: {
      label: metrics.companyContext.label,
      description: metrics.companyContext.description,
      figures: Object.fromEntries(
        metrics.companyContext.figures.map((figure) => [
          figure.id,
          { label: figure.label, note: figure.note },
        ]),
      ) as Node,
    },
    engagement: {
      label: metrics.engagement.label,
      description: metrics.engagement.description,
      figures: Object.fromEntries(
        metrics.engagement.figures.map((figure) => [
          figure.id,
          { label: figure.label, value: figure.value, change: figure.change, note: figure.note },
        ]),
      ) as Node,
      notPublished: Object.fromEntries(
        metrics.engagement.notPublished.map((row) => [
          row.id,
          { label: row.label, reason: row.reason },
        ]),
      ) as Node,
    },
  },
};

const rendered = `${JSON.stringify(dictionary, null, 2)}\n`;
const check = process.argv.includes("--check");

if (check) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    console.error("src/i18n/locales/en/data.json is missing. Run: npm run i18n:sync-data");
    process.exit(1);
  }
  if (current !== rendered) {
    console.error(
      "src/i18n/locales/en/data.json is out of date with src/data/*.json.\n" +
        "Run `npm run i18n:sync-data`, then translate any changed key in the six other locales.",
    );
    process.exit(1);
  }
  const count = rendered.match(/": "/g)?.length ?? 0;
  console.log(`data dictionary in sync — ${count} string(s) mirrored from src/data/`);
} else {
  writeFileSync(OUT, rendered, "utf8");
  console.log(`wrote ${OUT}`);
}
