import { getRateValue, minimumEarnedRobux } from "@/lib/calculations/rate-registry";
import { standardRateId } from "@/lib/calculations/devex";
import { formatCurrency, formatRate, formatRobux } from "@/lib/calculations/format";
import { Rational } from "@/lib/calculations/rational";
import { getTranslator } from "@/i18n/get-dictionary";
import { DEFAULT_LOCALE, getLocaleMeta } from "@/i18n/config";
import { resolveRenderableLocale } from "@/i18n/visibility";
import { OG_CONTENT_TYPE, OG_SIZE, renderOgImage } from "@/lib/og/template";

/**
 * The Open Graph card for a page under a language prefix.
 *
 * A link shared into a Brazilian group chat previewed in English, because all
 * seven languages pointed at the one card generated for the English site. The
 * preview is the whole of what most people see before deciding whether to
 * click, so an English card on a Portuguese page is the first — and often the
 * only — thing a reader is shown.
 *
 * **Re-exported from one `opengraph-image.tsx` per localized segment**, which
 * looks like duplication and is the only arrangement that works. Two others
 * were tried:
 *
 *   A single `opengraph-image.tsx` at the `[locale]` segment. The metadata
 *   file convention is not inherited by nested routes, so `/pt-br/` got a
 *   Portuguese card and `/pt-br/devex-rates/` got none at all.
 *
 *   A route handler at `/{locale}/og-card/`, which gives one stable URL per
 *   language. It works, and it costs 3.25 MB of Worker: a route handler is
 *   part of the server bundle whether or not it is `force-static`, and this
 *   one drags in `@vercel/og`'s edge build. That is over Cloudflare's 3 MB
 *   limit — the whole site failing to deploy so that a preview image can be
 *   generated by a Worker that will never be asked to generate it.
 *
 * The file convention prerenders instead: every card is a PNG on the CDN, and
 * nothing about it exists at runtime. Each re-export file is three lines, and
 * `scripts/i18n/sync-localized-og.ts` writes them, so a new localized route
 * cannot quietly ship without a card.
 *
 * One card per language rather than one per language per route. The eight
 * per-route English cards each state the figure their page exists to state;
 * matching that across six more languages is forty-eight images and forty-
 * eight more strings to keep in step with a rate that moves. This carries the
 * same worked example the site card does, in the reader's language and with
 * the figures formatted for it — which is the part that was wrong.
 */

export const runtime = "nodejs";
export const dynamic = "force-static";
export const size = OG_SIZE;
export const contentType = OG_CONTENT_TYPE;

const WORKED_EXAMPLE = 100_000;

interface LocaleParams {
  readonly params: Promise<{ readonly locale: string }>;
}

/**
 * Falls back rather than 404s.
 *
 * These routes are generated from the layout's own list of locales, so an
 * unresolvable segment cannot be requested. Next probes the metadata generator
 * while collecting page data, with a segment that is not yet one of them, and
 * throwing there fails the build rather than any reader's request.
 */
async function localeFrom({ params }: LocaleParams) {
  return resolveRenderableLocale((await params).locale) ?? DEFAULT_LOCALE;
}

export async function generateImageMetadata(props: LocaleParams) {
  const t = await getTranslator(await localeFrom(props), ["seo"]);
  return [{ id: "card", alt: t("seo.og.alt"), size, contentType }];
}

export default async function LocalizedOpengraphImage(props: LocaleParams) {
  const locale = await localeFrom(props);
  const t = await getTranslator(locale, ["seo"]);
  const tag = getLocaleMeta(locale).bcp47;
  const rate = getRateValue(standardRateId);
  const example = Rational.fromInt(WORKED_EXAMPLE).mul(rate);

  return renderOgImage({
    headline: [t("seo.og.headlineFirst"), t("seo.og.headlineSecond")],
    detail: t("seo.og.detail", {
      robux: formatRobux(tag, WORKED_EXAMPLE),
      usd: formatCurrency(tag, example, "USD"),
      rate: `$${formatRate(tag, rate)}`,
    }),
    footnote: t("seo.og.footnote", { minimum: formatRobux(tag, minimumEarnedRobux) }),
  });
}
